version: '3.9'

services:
  proyectoweb:
    container_name: proyectoweb
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./proyectoweb:/proyectoweb
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./env_files/.env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./env_files/.env